export const mockFavoritesData = [
  {
    _id: 1,
    burnedCalories: '312',
    time: '3',
    bodyPart: 'Waist',
    target: 'Abs',
  },
  {
    _id: 2,
    burnedCalories: '312',
    time: '3',
    bodyPart: 'Waist',
    target: 'Abs',
  },
  {
    _id: 3,
    burnedCalories: '312',
    time: '3',
    bodyPart: 'Waist',
    target: 'Abs',
  },
  {
    _id: 4,
    burnedCalories: '312',
    time: '3',
    bodyPart: 'Waist',
    target: 'Abs',
  },
  {
    _id: 5,
    burnedCalories: '312',
    time: '3',
    bodyPart: 'Waist',
    target: 'Abs',
  },
  {
    _id: 6,
    burnedCalories: '312',
    time: '3',
    bodyPart: 'Waist',
    target: 'Abs',
  },
  {
    _id: 7,
    burnedCalories: '312',
    time: '3',
    bodyPart: 'Waist',
    target: 'Abs',
  },
  {
    _id: 8,
    burnedCalories: '312',
    time: '3',
    bodyPart: 'Waist',
    target: 'Abs',
  },
  {
    _id: 9,
    burnedCalories: '312',
    time: '3',
    bodyPart: 'Waist',
    target: 'Abs',
  },
  {
    _id: 10,
    burnedCalories: '312',
    time: '3',
    bodyPart: 'Waist',
    target: 'Abs',
  },
  {
    _id: 11,
    burnedCalories: '312',
    time: '3',
    bodyPart: 'Waist',
    target: 'Abs',
  },
  {
    _id: 12,
    burnedCalories: '312',
    time: '3',
    bodyPart: 'Waist',
    target: 'Abs',
  },
  {
    _id: 13,
    burnedCalories: '312',
    time: '3',
    bodyPart: 'Waist',
    target: 'Abs',
  },
  {
    _id: 14,
    burnedCalories: '312',
    time: '3',
    bodyPart: 'Waist',
    target: 'Abs',
  },
  {
    _id: 15,
    burnedCalories: '312',
    time: '3',
    bodyPart: 'Waist',
    target: 'Abs',
  },
  {
    _id: 16,
    burnedCalories: '312',
    time: '3',
    bodyPart: 'Waist',
    target: 'Abs',
  },
  {
    _id: 17,
    burnedCalories: '312',
    time: '3',
    bodyPart: 'Waist',
    target: 'Abs',
  },
  {
    _id: 18,
    burnedCalories: '312',
    time: '3',
    bodyPart: 'Waist',
    target: 'Abs',
  },
];
