export const mockFavoritesData = [
  {
    _id: 1,
    burnedCalories: '312',
    time: '3',
    name: 'air bike1',
    bodyPart: 'Waist',
    target: 'Abs',
  },
  {
    _id: 2,
    burnedCalories: '312',
    time: '3',
    name: 'Air bike2',
    bodyPart: 'Waist',
    target: 'Abs',
  },
  {
    _id: 3,
    burnedCalories: '312',
    time: '3',
    name: 'Air bike3',
    bodyPart: 'Waist',
    target: 'Abs',
  },
  {
    _id: 4,
    burnedCalories: '312',
    time: '3',
    name: 'Air bike4',
    bodyPart: 'Waist',
    target: 'Abs',
  },
  {
    _id: 5,
    burnedCalories: '312',
    time: '3',
    name: 'Air bike5',
    bodyPart: 'Waist',
    target: 'Abs',
  },
  {
    _id: 6,
    burnedCalories: '312',
    time: '3',
    name: 'Air bike6',
    bodyPart: 'Waist',
    target: 'Abs',
  },
  {
    _id: 7,
    burnedCalories: '312',
    time: '3',
    name: 'Air bike7',
    bodyPart: 'Waist',
    target: 'Abs',
  },
  {
    _id: 8,
    burnedCalories: '312',
    time: '3',
    name: 'Air bike8',
    bodyPart: 'Waist',
    target: 'Abs',
  },
  {
    _id: 9,
    burnedCalories: '312',
    time: '3',
    name: 'Air bike9',
    bodyPart: 'Waist',
    target: 'Abs',
  },
  {
    _id: 10,
    burnedCalories: '312',
    time: '3',
    name: 'Air bike10',
    bodyPart: 'Waist',
    target: 'Abs',
  },
  {
    _id: 11,
    burnedCalories: '312',
    time: '3',
    name: 'Air bike11',
    bodyPart: 'Waist',
    target: 'Abs',
  },
  {
    _id: 12,
    burnedCalories: '312',
    time: '3',
    name: 'Air bike12',
    bodyPart: 'Waist',
    target: 'Abs',
  },
  {
    _id: 13,
    burnedCalories: '312',
    time: '3',
    name: 'Air bike13',
    bodyPart: 'Waist',
    target: 'Abs',
  },
  {
    _id: 14,
    burnedCalories: '312',
    time: '3',
    name: 'Air bike14',
    bodyPart: 'Waist',
    target: 'Abs',
  },
  {
    _id: 15,
    burnedCalories: '312',
    time: '3',
    name: 'Air bike15',
    bodyPart: 'Waist',
    target: 'Abs',
  },
  {
    _id: 16,
    burnedCalories: '312',
    time: '3',
    name: 'Air bike16',
    bodyPart: 'Waist',
    target: 'Abs',
  },
  {
    _id: 17,
    burnedCalories: '312',
    time: '3',
    name: 'Air bike17',
    bodyPart: 'Waist',
    target: 'Abs',
  },
  {
    _id: 18,
    burnedCalories: '312',
    time: '3',
    name: 'Air bike18',
    bodyPart: 'Waist',
    target: 'Abs',
  },
];
